config/routes.rb
Sandbox::Application.routes.draw do
  root :to => "pages#home"
  
  resources :posts
  
  match '/simple', :to => "pages#simple"
  match '/resources', :to => "pages#resources"

end

app/models/post.rb
class Post < ActiveRecord::Base    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = 'home'
  end
  
  def simple
    @title = 'simple js'
    @heading = 'simple js features'
  end
  
  def resources
    @title = 'resources'
    @heading = 'project resources'
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  respond_to :html, :js, :xml
  
  def index
    @title = 'posts'
    @header = 'posts'
    @post = Post.new
    @search = Post.search(params[:search])
    @posts = @search.all.sort_by{|t| - t.created_at.to_i}
    respond_with(@posts)
  end

  def create
    @new_post = Post.new(params[:post])
    @new_post.save
    @updated_posts = Post.all.sort_by{|t| - t.created_at.to_i}
    respond_with(@updated_posts)
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post_id = @post.id
    @post.destroy
    respond_with(@post_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<div class="holder">
	<table style="width: 1000px">
		<tr>
			<td style="padding-top: 13px; padding-bottom: 1px">
				<div class="logo"><%= link_to 'sandbox', root_path %></div>
			</td>
			<td style="text-align: right">
				<% unless @title == 'home' %>
				<nav style="margin-right: -30px">
					<ul>
						<li><%= link_to 'resources', resources_path %></li>
						<li><%= link_to 'posts', posts_path %></li>
						<li><%= link_to 'modal', '#' %></li>
						<li><%= link_to 'validation', '#' %></li>
					</ul>
				</nav>
				<% end %>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				test site for learning javascript, jquery, ajax, and other rich internet stuff
			</td>
		</tr>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<%= yield :head%>

<head>
  	<title><%= @title %></title>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
  	<link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
</head>
<body>
	
<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="holder">
	<br>
	<table>
		<tr>
			<td style="padding-right: 10px">
				<%= link_to 'simple js elements', simple_path, :class => 'dash_box' %>		
			</td>
			<td style="padding-right: 10px; padding-left: 10px">
				<%= link_to 'posts', posts_path, :class => 'dash_box' %>	
			</td>
			<td style="padding-right: 10px; padding-left: 10px">
				<%= link_to 'modal input', '#', :class => 'dash_box' %>
			</td>
			<td style="padding-left: 10px">
				<%= link_to 'input validation', '#', :class => 'dash_box' %>
			</td>
		</tr>
	</table>
	<br>
</div>


<script>

	$(".dash_box").mouseover(function(){
		$(this).css("background-color","#F8F8F8");
	});
	
	$(".dash_box").mouseout(function(){
		$(this).css("background-color","#FFFFFF");
	});
	
	$("#test").click(function(){
		$(this).window.location.href="http://www.google.com";
	})
			

	</script>

app/views/pages/resources.html.erb
<div class="holder">
	<h1><%= @heading %></h1>
	
	<div class="cursorbox" id="jqslide" onmouseover="hoveron()" onmouseout="hoveroff()">
		search
		<div class="slider" style="display: none">
			<%= link_to 'metasearch', 'http://erniemiller.org/projects/metasearch/', :target => '_blank' %>
			<p>metasearch is extensible searching for your form_for enjoyment. it “wraps” one of your activerecord models, providing methods that allow you to build up search conditions against that model, and has a few extra form helpers to simplify sorting and supplying multiple parameters to your condition methods as well.</p>
			<%= link_to 'railscast #240: search, sort, paginate with ajax', 'http://railscasts.com/episodes/240-search-sort-paginate-with-ajax', :target => '_blank' %>
			<p>many administration pages have search, sorting, and pagination on the index page. see how to add all of this including ajax.</p>
			<%= link_to 'railscast #228: sortable table columns', 'http://railscasts.com/episodes/228-sortable-table-columns', :target => '_blank' %>
			<p>here i walk you through adding the ability to sort table columns in ascending or descending order by clicking the header.</p>
		</div>
	</div>
	<div class="cursorbox" id="jqslide" onmouseover="hoveron()" onmouseout="hoveroff()">
		test box
		<div class="slider" style="display: none; font-size: 65%">
			random text that slides down when the box is clicked.
		</div>
	</div>
</div>

<script>

	
	$(".cursorbox").click(function(){
		$(this).children("div").slideToggle();
	});

	$(".cursorbox").mouseover(function(){
		$(this).css("background-color","#F8F8F8");
	});
	
	$(".cursorbox").mouseout(function(){
		$(this).css("background-color","#FFFFFF");
	});
	
	$('.slider').css('padding-top', '5px')
	
	$('p').css('margin-top', '0px');
	$('p').css('font-size', '75%');
	
</script>

app/views/pages/simple.html.erb
<div class="holder">
	<h1><%= @heading %></h1>
	
	<div class="cursorbox" id="jqslide" onmouseover="hoveron()" onmouseout="hoveroff()">
		jquery slide
		<div id="slider" style="display: none; font-size: 65%">
			this element slides up and down using jquery. i used javascript to code the hover effect, which probably isn't the most effective way.
		</div>
	</div>
	
	<div class="box">
		js multiply
		<%= text_field_tag 'x', nil %>
		x
		<%= text_field_tag 'y', nil %>
	
		<button onclick="multiply()">Execute</button>
		=
		<span id="answer">product</span>
	</div>
	<div class="box">
		jquery hide
		<button id="toggle">hide/show</button>
		<span id="jhide" style="font-size: 65%">this text can be hidden and unhidden using jquery</span>
	</div>
	<div class="box">
		jquery animation
		<button id="play">play</button>
		<button id="reset">reset</button>
		<span id="film" style="font-size: 65%">this is a simple animation using jquery</span>
	</div>
</div>

<script>
	$("#play").click(function(){
		$("#film").animate({
			fontSize:'50%',
			opacity:'0.5'
		});
	});
	
	$("#reset").click(function(){
		$("#film").css({
			'font-size':'65%',
			'opacity':'1.0'
		});
	});
	
	$("#jqslide").click(function(){
		$("#slider").slideToggle();
	});
	
	$("#toggle").click(function(){
 		$("#jhide").fadeToggle(500);
	});
	
	function multiply()	{
		var x = document.getElementById("x").value
		var y = document.getElementById("y").value
		document.getElementById("answer").innerHTML=x*y
	}
	
		function hoveron()	{
		document.getElementById("jqslide").style.background="#F8F8F8"
	}
		
	function hoveroff()	{
		document.getElementById("jqslide").style.background="#FFFFFF"
	}
	
</script>

app/views/posts/_form.html.erb
<div class="box">
	<%= form_for @post, :remote => true do |f| %>
		<%= f.text_field :body %>
		<%= f.submit 'create post', :id => 'post_button' %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<%= div_for(post) do %>
	<%= post.body %>
	<%= link_to 'delete', post, :method => :delete, :remote => true, :class => 'post_delete' %>
<% end %>

app/views/posts/create.js.erb
$('#post_div').html('<%= escape_javascript(render(@updated_posts)) %>');
$('.post:first').hide();
$('.post:first').slideDown('slow');
$('#post_body').val('')


$(".post").mouseover(function(){
	$(this).css("background-color","#F8F8F8");
	$(this).children("a").toggle();
});
	
$(".post").mouseout(function(){
	$(this).css("background-color","#FFFFFF");
	$(this).children("a").toggle();
});

app/views/posts/destroy.js.erb
$('.post_delete').bind('ajax:success', function(){
	$(this).closest('div').slideUp('slow');
});

app/views/posts/index.html.erb
<div class="holder">
	
	<h1><%= @header %></h1>

	<%= render '/posts/form'%>
	
	<%= form_for @search, :remote => true do |f| %>
		<%= f.text_field :body_contains %>
	<% end %>
		
	<div id="post_div">
		<%= render @posts %>		
	</div>
		
</div>


<script>
	
$("#post_search input").keyup(function(){
	$(this).submit();
});

	
</script>

app/views/posts/index.js.erb
$("#post_div").html("<%= escape_javascript(render(@posts)) %>")

$(function(){
	$(".post").mouseover(function(){
		$(this).css("background-color","#F8F8F8");
		$(this).children("a").toggle();
	});
	
	$(".post").mouseout(function(){
		$(this).css("background-color","#FFFFFF");
		$(this).children("a").toggle();
	});
	
	$('.post_delete').click(function(){
		$(this).parent.hide();
	});
});